### ISSUE TITLE
Leia To-Do

### ISSUE THREAD

**Issue by ghost** [BigNoid/script.skinshortcuts#217]
To-do list for Leia era version of script, to be kept updated as issues and to-do's are identified.

- [ ] Error message shown when attempting to make labelID changes to existing menu items [[log 1](http://pastebin.com/yDc4wyiy)] [[log 2](http://pastebin.com/5t0VyyG7)], possibly linked to new universal 'attempt' method
- [ ] Removed library.py function scriptPlaylists still referenced from GUI 310 (should this function have been removed?) [[log](http://pastebin.com/SkgGMh4x)]
- [ ] Removed import 'gmtime' still referenced from GUI 405 [[log](http://pastebin.com/SkgGMh4x)]

**Comment by MikeSiLVO** [comment]
Some more errors...

Full Log Below.

If you need a test monkey just let me know 😃

**Comment by ghost** [comment]
Full debug logs only please :)

Any testing is hugely appreciated, though be prepared that development is slow right now ;)

**Comment by MikeSiLVO** [comment]
@Ignoble61 Sorry should have just posted it but was being lazy...

**[LOG](http://pastebin.com/SkgGMh4x)**

I pressed GUI buttons 310 and 405 thrice in the log posted above.

I understand that Leia is still pre-alpha and am not trying to rush any fixes just provide some info for when someone has the time and inclination to look into it :smiley:

**Comment by ghost** [comment]
> I understand that Leia is still pre-alpha and am not trying to rush any fixes just provide some info for when someone has the time and inclination to look into it 😃

And it's appreciated. I just want to make sure expectations are set as, right now, I simply don't have the ability to spend the time needed to get this all finished :) To-do updated with the relevant issues.
